using System;
using System.Collections.Generic;

namespace HistoriCrawl.Portable
{
	public static class MarkerData
	{
		public static List<Marker> Markers { get; private set; }

		static MarkerData()
		{
			Markers = new List<Marker>();

			Markers.Add(new Marker {Number = 1, Title = "HEATON'S STATION", Location = "Lock No. 1 Road at end of Seminary Avenue", MarkerText = "On this bluff in 1780, pioneers who came with James Robertson built Heaton’s (also spelled Eaton’s) station.  It and two other forts (Nashborough and Freedland’s) withstood all Indian attacks and saved the Cumberland settlements.  On the river below were successively a buffalo ford, ferry, and Lock 1.  The home of Amos Heaton stood 100 feet north.", Latitude = "36.199949", Longitude = "-86.78763" });
			Markers.Add(new Marker {Number = 2, Title = "CAPTAIN JOHN RAINS Pioneer hunter and settler", Location = "SW corner of Rains Avenue and Merritt Street", MarkerText = "On Christmas 1779 he led his family and livestock across the frozen Cumberland and settled in this vicinity.  In 1784 he built a fort that enclosed the spring 75 yards east.  At James Robertson’s orders he often led a company of scouts against Indians.  His home was on this hill until he died in 1834, age 91.", Latitude = "36.13908", Longitude = "-86.76404" });
			Markers.Add(new Marker {Number = 3, Title = "SITE OF FIRST STORE", Location = "NE corner of Second Avenue North and Banks Street", MarkerText = "Lardner Clark came from Philadelphia in the early 1780’s with ten horses packed with piece goods, needles and pins.  He established Nashville’s first drygoods store by 1786, on a site 30 yards east.  The building, which served as store, tavern and dwelling, faced south and was known as “the house with the piazza.” 1786 date incorrect. Should have been 1783, per documentation on file.", Latitude = "36.165123", Longitude = "-86.777237" });
			Markers.Add(new Marker {Number = 4, Title = "NASHVILLE PLOW WORKS", Location = "SE corner of Eighth Avenue South and Palmer Place", MarkerText = "Site of a farm implement factory operated by Messrs. Sharp and Hamilton, previous to the War Between the States.  With the out-break of hostilities they reversed the Biblical injunction and produced swords of excellent quality for the Confederacy.  With the coming of the Federal Army, the making of swords was discontinued.", Latitude = "36.153444", Longitude = "-86.779458" });
			Markers.Add(new Marker {Number = 5, Title = "BATTLE OF NASHVILLE Shy's Hill", Location = "W side of Benton Smith Rd, South of Harding Place at bottom of Shy’s Hill Tl.", MarkerText = "On this hill was fought the decisive encounter of the Battle of Nashville December 16, 1864.  At 4:15 p.m. a Federal assault at the angle on top of the hill broke the Confederate line.  Col. W. M. Shy, 20th Tenn. Inf. was killed and Gen. T. B. Smith was captured.  The Confederates retreated over the Overton Hills to the Franklin Pike.", Latitude = "36.088026", Longitude = "-86.808237" });
			Markers.Add(new Marker {Number = 6, Title = "BATTLE OF NASHVILLE Stewart’s Line", Location = "corner of Granny White Pike and Sewanee Rd.", MarkerText = "Loring’s division of Stewart’s Corps, Hood’s Confederate Army of Tennessee, fought behind this stone wall Dec. 16, 1864.  All Federal attacks were beaten back until the Confederate line was broken a mile to the west.  The division retreated south through the hills toward Brentwood.", Latitude = "36.086529", Longitude = "-86.803815" });
			Markers.Add(new Marker {Number = 7, Title = "EAST NASHVILLE FIRE", Location = "E side of North First Street,  North of OldhamStreet intersection, across from Capitol LumberCo. building.", MarkerText = "Nashville’s worst disaster by fire occurred Wednesday, March 22, 1916. It began at 11:47 a.m. in the rear of Seagraves Planing Mill, 80 yards west, and was swept eastwardly by 44 to 51 mph gales.  It was brought under control at 4:30 p.m. near So. Tenth and Dew Streets.  648 buildings were burned, 1 life lost and 3,000 people left homeless.", Latitude = "36.175226", Longitude = "-86.774255" });
			Markers.Add(new Marker {Number = 8, Title = "THE NASHVILLE RACE COURSE", Location = "Vantage Way and Great Circle Rd. near Bush Lake.", MarkerText = "The Nashville Race Course, the “Burns Island Track,”   1828-1884, was .6 of a mile north.  Here Oct. 10, 1843, was run the then richest race in the world, the $35,000 Peyton Stakes, 4 mile heats, promoted by Bailie Peyton.  The winner owned by Thomas Kirkman, was renamed “Peytona.”  Ten Broeck and Thora also raced here. ", Latitude = "36.193084", Longitude = "-86.790799" });
			Markers.Add(new Marker {Number = 9, Title = "HOLY TRINITY EPISCOPAL CHURCH", Location = "615 Sixth Avenue South", MarkerText = "This building, renowned for its pure Gothic architecture and harmony of proportions, was designed by Wills & Dudley, of New York, in a style suggesting an English village church.  The cornerstone was laid May 7, 1852, by Bishop James Otey.  The church was used as a powder magazine by the Union Army for several months during the Civil War.", Latitude = "36.153183", Longitude = "-86.775587" });
			Markers.Add(new Marker {Number = 10, Title = "TWO RIVERS MANSION", Location = "In front of Two Rivers Mansion at 3130 McGavock Pike", MarkerText = "Built in 1859 by David H. McGavock, this mansion stands on land inherited by McGavock’s wife, Willie, from her father, William Harding.  The smaller house to the left was built in 1802.  Dr. James Priestley’s Academy, established about 1816, was located on the 1,100 acre farm 1 mile from the mansion on the Cumberland River bluff.", Latitude = "36.18974", Longitude = "-86.677263" });
			Markers.Add(new Marker {Number = 11, Title = "SAMUEL WATKINS1794-1880", Location = "2298 Rosa L Parks Blvd 36.193756, -86.806218", MarkerText = "", Latitude = "36.193756", Longitude = "-86.806218" });
			Markers.Add(new Marker {Number = 12, Title = "NASHVILLE’S FIRST PUBLIC SCHOOL", Location = "Hume-Fogg High School, 700 Broadway", MarkerText = "Nashville’s first public school, Hume School, opened here Feb. 26, 1855.  A three story brick building, the school employed 12 teachers and served all grades.  In 1874 high school classes were moved to Fogg School built on adjoining corner lot. Named for educators, Alfred E. Hume & Francis B. Fogg, the schools were replaced by Hume-Fogg in 1912.", Latitude = "36.159303", Longitude = "-86.781572" });
			Markers.Add(new Marker {Number = 13, Title = "MRS. JOHN DONELSON", Location = "Gallatin Pike (Hwy 31) near Myatt Drive intersection", MarkerText = "After Col. John Donelson was killed in 1785, his widow and family continued to live here in a log house.  In 1789 lawyers Andrew Jackson and John Overton boarded with the Donelsons.  Here Jackson met Rachel, the Donelson’s youngest daughter.  They married in 1791 and lived here until they acquired there own home across the Cumberland in 1792.", Latitude = "36.296439", Longitude = "-86.699898" });
			Markers.Add(new Marker {Number = 14, Title = "NASHVILLE CENTENNIAL 1780-1880", Location = "SW corner of intersection of Broadway and Eighth Avenue.", MarkerText = "The Centennial Exposition on this site in 1880 from April 23 through May 30, marked a century of progress since the founding of Nashville.  There were parades, oratory, music; historical, art and commercial exhibits; theatrical performances, and “the grandest display of fireworks ever seen in Nashville.”", Latitude = "36.158648", Longitude = "-86.782508" });
			Markers.Add(new Marker {Number = 15, Title = "POWDER-GRINDING WHEELS", Location = "Near present position of wheels in Centennial Park, by Park Plaza entrance", MarkerText = "These wheels used by the Confederacy to grind gunpowder at Augusta, Ga., in 1863-1864 were made in Woolwich, England and were shipped on the blockade runner “Spray,” via Mobile. After the war Gen. Miles purchased them for use at Sycamore Powder Mills, Cheatham County. They were exhibited at the Tennessee Centennial Exposition in 1897.", Latitude = "36.153003", Longitude = "-86.813964" });
			Markers.Add(new Marker {Number = 16, Title = "BELMONT MANSION", Location = "Belmont Campus in front of the mansion", MarkerText = "", Latitude = "36.135298", Longitude = "-86.794819" });
			Markers.Add(new Marker {Number = 17, Title = "CHICKASAW TREATY", Location = "Corner of Morrow Road and Terry Drive", MarkerText = "In 1783, Chickasaw chiefs met with white settlers at a spring 100 yards north and agreed on land rights—the Cumberland country for the settlers, the Tennessee River lands beyond the Duck River ridge for the Chickasaw. This tribe became firm friends of James Robertson and his people, but the settlement suffered many more raids by Cherokees and Creeks.", Latitude = "36.163513", Longitude = "-86.863273" });
			Markers.Add(new Marker {Number = 18, Title = "JOHNSON'S STATION", Location = "Harding Pike/ Memphis-Bristol Hwy and Vine Court", MarkerText = "A double log house and a few log cabins, partially picketed, stood here about 1790. On May 9, 1793, 4 children on their way to the spring were attacked by Indians. Three were scalped and killed. One escaped. The home of Charles Bosley, wealthy pioneer and a member of the Nickajack Expedition, later stood on this site.", Latitude = "36.129816", Longitude = "-86.839489" });
			Markers.Add(new Marker {Number = 19, Title = "MEHARRY MEDICAL COLLEGE", Location = "Meharry Medical College, D.B. Todd Boulvard entrance.", MarkerText = "Meharry Medical College, established in 1876 through the efforts of Dr. George W. Hubbard, Dr. William J. Sneed, and Samuel Meharry, is the only AMA Accredited, privately endowed, predominantly Negro medical school in the world. During its first 90 years of service, it trained more Negro physicians and dentists than any other institution.", Latitude = "36.166854", Longitude = "-86.805679" });
			Markers.Add(new Marker {Number = 20, Title = "RYMAN AUDITORIUM", Location = "Front wall of building", MarkerText = "Built 1891 as Union Gospel Tabernacle for religious revival meetings. Renamed Ryman Auditorium 1905 for steamboat captain Tom Ryman, the building’s chief contributor. The greatest musicians, actors, dancers, speakers, made the Ryman “the most famous one-night stand on the road.” Bought 1963 by WSM’s Grand Ole Opry which first performed here in 1941.", Latitude = "36.161149", Longitude = "-86.778818" });
			Markers.Add(new Marker {Number = 21, Title = "GLENDALE PARK", Location = "Intersection of Lealand and Tower Place", MarkerText = "Here, near the center of a 64-acre woodland park owned by the Nashville Railway & Light Co., the Glendale streetcar line turned back toward town.  The park opened in 1888 to attract passengers for the railway—originally steam, electric after 1893.  A zoo was added in 1912.  The park closed in 1932, a casualty of automobiles and the Depression.", Latitude = "36.096323", Longitude = "-86.790479" });
			Markers.Add(new Marker {Number = 23, Title = "CUMBERLAND PARK", Location = "State Fairgrounds 500 Wedgewood", MarkerText = "The Cumberland Fair and Racing Association sponsored harness racing here 1891-1894. The great match race between Hal Pointer of Tennessee and Direct of California occurred Oct. 21, 1891. Direct won all three heats in record time for a pacing race. Arion, Directum, Kremlin, Robt. J. raced here. Running races 1893-1906 preceded the State Fair 1906.", Latitude = "36.132745", Longitude = "-86.76492" });
			Markers.Add(new Marker {Number = 24, Title = "LOCKELAND SPRING", Location = "100 South Seventeenth Street", MarkerText = "Located 250 yds. S.E., this famous pioneer spring served Lockeland mansion on site of present school building. Home built by Col. Robert Weakley in early 1800’s and named for his wife, daughter of Gen. Matthew Locke of Salisbury, N.C. Spring water won prize at St. Louis Exposition in 1904, for its “unique mineral composition and salubrious quality.” ", Latitude = "", Longitude = "" });
			Markers.Add(new Marker {Number = 25, Title = "TRANSFER STATION SITE", Location = "Near corner of 3rd Ave. and Deaderick St.", MarkerText = "Site of electric street railway transfer station 1902-1940. Electric streetcar service began formally on April 30, 1889 replacing mule-drawn streetcars which had served the city since 1866. Final run for the electric streetcars was February 2, 1941 on Radnor line. Operation of bus system began Aug. 4, 1940 on Hillsboro-Sunset line", Latitude = "36.166454", Longitude = "-86.779287" });
		}
	}
}